---
# tasks file for hubot-slack
- name: Install dependencies.
  package:
    name: sudo
    state: present

- name: Install required Node.js packages.
  npm:
    name: "{{ item }}"
    state: present
    global: true
  with_items:
    - yo
    - generator-hubot

- name: Ensure hubot user exists.
  user:
    name: hubot
    create_home: true
    home: "{{ hubot_home }}"

- name: Generate hubot.
  command: >
    yo hubot
    --owner="{{ hubot_owner }}"
    --name="{{ hubot_name }}"
    --description="{{ hubot_description }}"
    --adapter=slack
    --defaults
    chdir={{ hubot_home }}
  become: true
  become_user: hubot

- name: Remove certain scripts from external-scripts.json
  lineinfile:
    path: "{{ hubot_home }}/external-scripts.json"
    regexp: "{{ item }}"
    state: absent
  with_items:
    - 'redis-brain'
    - 'heroku'
  become: true
  become_user: hubot

- name: Remove the hubot-scripts.json file.
  file:
    path: "{{ hubot_home }}/hubot-scripts.json"
    state: absent
